### ISSUE TITLE
Image Recognition

### ISSUE THREAD

**Issue by tylertomlinson** [my-fly-box/my-fly-box-api#24]
As a developer, I can receive a image of a catch, and store it in the database, and send it to the api, then receive back a percentage of type of species that catch is.

- [x] [Storing Users Image](#28)
- [x] [Control Images for Learning ](#27)
- [x] [Sending Users Image ](#29)
- [x] [Percentage of Users Image](#30)
